### ISSUE TITLE
Missed Steps in documentation

### ISSUE THREAD

**Issue by sMustafov** [tomw1808/blocktactoe#1]
In the documentation before the 7th step "truffle develop", you should go to /contracts folder and compile them. With the command "compile" if you are in the truffle developers console or "truffle develop". 
Am I right?

**Comment by tomw1808** [comment]
AFAIK, the contracts can also be compiled inside the truffle developer console, not sure if they really have to be compiled _before_ going to "truffle develop". You don't need to change to the contracts folder for that, it should work also outside.
