### ISSUE TITLE
Modifier

### ISSUE THREAD

**Issue by sMustafov** [tomw1808/blocktactoe#4]
https://github.com/tomw1808/blocktactoe/blob/c3d471a6e10574b6b6a71e31e5a60346bd0b9d8d/contracts/TicTacToe.sol#L32 we can make it a modifier.

**Comment by tomw1808** [comment]
You can make it a modifier if you think it's beneficial in your contract, definitely. For this size of contract it doesn't really pay off and adds additional layers of complexity for the reader for my understanding.
