### ISSUE TITLE
Extract to a function

### ISSUE THREAD

**Issue by sMustafov** [tomw1808/blocktactoe#5]
https://github.com/tomw1808/blocktactoe/blob/c3d471a6e10574b6b6a71e31e5a60346bd0b9d8d/contracts/TicTacToe.sol#L78 we can extract the things in the if and in the else in a function which will get the balanceToWithdrawPlayer and player.

**Comment by tomw1808** [comment]
You can definitely do it. It's a question of design. I rather keep it like this.
